runtime: nodejs8

handlers:
  - url: /(.*\.(js|map|css|png|jpg|jpeg|gif|ico))$
    static_files: dist/WebAppClient/\1
    upload: dist/WebAppClient/(.*)

  - url: /assets
    static_dir: dist/WebAppClient/assets

  - url: .*
    static_files: dist/WebAppClient/index.html
    upload: dist/WebAppClient/index.html

